spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_center
    hikari:
      username: xxx
      password: xxx
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-lifetime: 600000
  cloud:
    nacos:
      discovery:
        # 指定Nacos的地址
        server-addr: 127.0.0.1:8848
        cluster-name: NJ
        metadata:
          v: 1.0
    # spring cloud stream 配置
#    stream:
#      rocketmq:
#        binder:
#          name-server: 127.0.0.1:9876
#      bindings:
#        input:
#          # 用来指定topic
#          destination: add-bonus
#          # 随便写，但如果用的是RocketMQ一定要配置，否则应用起不起来
#          group: saint-consumer
#        my-input:
#          destination: stream-my-topic
#          group: my-group
server:
  port: 8089
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # 小坑，必须制定group
    group: test-group
logging:
  level:
    com.alibaba.nacos: error
jwt:
  secret: saintaaaaa
  # 有效期，单位秒，默认两周
  expire-time-in-second: 1209600